# https://circleci.com/gh/{{ cookiecutter.github_username }}/{{ cookiecutter.repo_name }}

# NOTE: Don't forget to add COVERALLS_REPO_TOKEN in Circle-CI private env variables.
# https://circleci.com/gh/{{ cookiecutter.github_username }}/{{ cookiecutter.repo_name }}/edit#env-vars

machine:
  environment:
    # Python versions to tests (Maximum of 4 different versions)
    PY_VERSIONS:  "3.6 3.5 {% if cookiecutter.support_python_2 == 'y' %}2.7{% endif %}"
    # Environment variables used by astropy helpers
    TRAVIS_OS_NAME: "linux"
    CONDA_DEPENDENCIES_FLAGS: "--quiet"
    CONDA_DEPENDENCIES: "pytest pytest-cov"
    PIP_DEPENDENCIES: "coveralls pytest-qt pytest-xvfb"

dependencies:
  pre:
    # We need to run a window manager to avoid focus problems when running our tests.
    # See https://github.com/TestFX/TestFX/issues/158#issuecomment-62421691
    - sudo apt-get install matchbox-window-manager
  override:
    # First convert PY_VERSIONS to an array and then select the python version based on the CIRCLE_NODE_INDEX
    # pinstall pyqt5 using pip in the python 3.6 envpiroment
    - export PY_VERSIONS=($PY_VERSIONS) &&
      export TRAVIS_PYTHON_VERSION=${PY_VERSIONS[$CIRCLE_NODE_INDEX]} &&
      echo -e "PYTHON = $TRAVIS_PYTHON_VERSION \n============" &&
      git clone git://github.com/astropy/ci-helpers.git > /dev/null &&
      source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh &&
      export PATH="$HOME/miniconda/bin:$PATH" &&
      source activate test &&
      conda install -q ciocheck -c spyder-ide --no-update-deps &&
      if [ "$CIRCLE_NODE_INDEX" = "0" ]; then pip install -q pyqt5 spyder; else conda install -q -c spyder-ide spyder; fi &&
      python setup.py install > /dev/null;
    - DISPLAY=:99 /usr/bin/matchbox-window-manager:
        background: true
    - sleep 5

test:
  override:
    # Style checks
    - export PATH="$HOME/miniconda/bin:$PATH" && source activate test && ciocheck {{ cookiecutter.project_name }}: # note the colon
        parallel: true
    # Tests
    - export PATH="$HOME/miniconda/bin:$PATH" && source activate test && pytest {{ cookiecutter.project_name }}: # note the colon
        parallel: true
    # Coveralls
    - export PATH="$HOME/miniconda/bin:$PATH" && source activate test && coveralls: # note the colon
        parallel: true
